apiVersion: v1
kind: PersistentVolume
metadata:
  name: datastore-pv
  namespace: kubeflow
spec:
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: datastore
  capacity:
    storage: 300Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: "/media/ryan/ColdStorage/datastore"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datastore-pvc
  namespace: ryan-env
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: datastore
  resources:
    requests:
      storage: 300Gi
